### PR TITLE
checkbox global setting to mute death alert sounds

### LINKED ISSUE #291: "Low-Intrusion" mode and other sensory adjustments
The alert is quite startling and can sometimes covering portions of the screen at the worst time.

Proposal: "Low-Intrusion" customisations, allowing the player to choose:
- Where on screen the alert is positioned
- The size of the alert
- Which sound is played, if any
- .. and so forth

The already-used Ace3 libraries make such configuration via the Interface Options -> AddOns panel straight-forward, and provides excellent groundwork for catering to many groups of special needs and personal tastes without compromising the challenge.

### LINKED ISSUE #491: Update minimum alert level description
image
This could be easier to understand -- I did not have any idea what this setting did until I looked at the source code.

### PR DESCRIPTION
**Pull request by isaiahsherfick**
(mostly) resolves #291 
resolves #491 
Simply adds a checkbox to Interface Options > Hardcore > Alerts allowing the user to silence the death alert sound.

image

### CODE REVIEW

**Comment by isaiahsherfick** [comment]
now also resolves #491

**Comment by aaronma37** [comment]
Will rebase and merge soon

**Comment by isaiahsherfick** [comment]
Thanks!

**Comment by aaronma37** [comment]
ah, sorry. Can you rebase first? Ill merge after. I thought I could resolve the conflicts

**Comment by isaiahsherfick** [comment]
@aaronma37 fixed the conflicts. Lmk if I need to do anything else. Thanks!

**Comment by aaronma37** [comment]
Np! Sorry about not seeing this before the version drop

**Pull request merged**
