### PR TITLE
Recovery codes 

### PR DESCRIPTION
**Pull request by aaronma37**
Added recovery codes from screenshots.  Player can also visit the menu tab to get a recovery code at any time. Fixed accountability UI

Recovers 
* time tracked
* start date
* achievements

### CODE REVIEW

**Comment by aaronma37** [comment]
image

**Comment by zdeyn** [comment]
This looks really good - is there any way we can extend it to cover the dungeon tracker data too? perhaps @frankdj100 might want to make a patch for that?

**Comment by frankdj100** [comment]
There's a bit more information in the dungeon data. Time tracked and start date are just two integers, and the achievements probably just coded into 0/1 bits. That string will become a lot bigger with the wealth of data in the dungeon log. But I'll think about which ones are most important. Definitely just a 0/1 bit for "dungeon completed" can be done. Wouldn't add a whole lot over the legacy quest system (just things like SFK for alliance), but lemme brood on that a bit.

**Comment by frankdj100** [comment]
Just as a reminder: we need to add a version number (1 character) and also time of the recovery string generation (can do in seconds since 1 April 2023 to save some bit space, or just allocate 32 bit and use normal 1970 epoque start date)

**Comment by frankdj100** [comment]
One other thing to help protect the security. Give each recovery string an ID (=counter). Store the last issued recovery string ID (a counter) in the data file. Or, alternatively, each recovery string can include the last saved recovery string’s ID (corresponding to last /reload). Then, a mod can ask for all the recovery strings since the last /reload, to see what happened. Prevents some selective restoration abuses.

**Comment by aaronma37** [comment]
> Just as a reminder: we need to add a version number (1 character) and also time of the recovery string generation (can do in seconds since 1 April 2023 to save some bit space, or just allocate 32 bit and use normal 1970 epoque start date)

What is the motivation for version#? Id think that we would want the strings to be backward and forward compatable if possible

**Comment by aaronma37** [comment]
> One other thing to help protect the security. Give each recovery string an ID (=counter). Store the last issued recovery string ID (a counter) in the data file. Or, alternatively, each recovery string can include the last saved recovery string’s ID (corresponding to last /reload). Then, a mod can ask for all the recovery strings since the last /reload, to see what happened. Prevents some selective restoration abuses. Also good to prevent applying a delta to the wrong reference.

In the situation that was of concern, where the player deletes their savedata to try to abuse this, wouldn't this counter get removed anyways?  Afaik there isnt a scenario where the code is abused after there is a successful reload. How would a mechanism like this be handled for multicpu setups?

**Comment by aaronma37** [comment]
Alternatively, we could take the dive and just release the third party app. I do think the downsides of externals dependencies outweighs the benefits, but multicpu/dataloss needs to be dealt with

image

**Comment by frankdj100** [comment]
> > Just as a reminder: we need to add a version number (1 character) and also time of the recovery string generation (can do in seconds since 1 April 2023 to save some bit space, or just allocate 32 bit and use normal 1970 epoque start date)
> 
> What is the motivation for version#? Id think that we would want the strings to be backward and forward compatable if possible

Mostly, we’ll be aiming for a minimum length string, so we don’t have space for a self describing format. Suppose we want to add another 3 chars of info, or a different hash code algo, then the interpretation of the chars is different.

**Comment by frankdj100** [comment]
> > One other thing to help protect the security. Give each recovery string an ID (=counter). Store the last issued recovery string ID (a counter) in the data file. Or, alternatively, each recovery string can include the last saved recovery string’s ID (corresponding to last /reload). Then, a mod can ask for all the recovery strings since the last /reload, to see what happened. Prevents some selective restoration abuses. Also good to prevent applying a delta to the wrong reference.
> 
> In the situation that was of concern, where the player deletes their savedata to try to abuse this, wouldn't this counter get removed anyways? Afaik there isnt a scenario where the code is abused after there is a successful reload. How would a mechanism like this be handled for multicpu setups?

True. The counter is not useful for recovery of full data loss. But it helps with partial loss to make sure a recovery with delta blocks doesn’t get applied to the wrong reference reload.

I would not allow use of recovery strings for multi cpu. We just can’t stuff the entire data file in one 20 character string.

**Pull request closed without merging**
