### PR TITLE
Duo trio range fix

### PR DESCRIPTION
**Pull request by zdeyn**
Code is enforcing a sub-zone level bonding between duo and trio partners

I've modified the code to allow the same zone, not subzone - this is the same as allowing a duo to be Stormwind and Goldshire (same zone id, different subzone), but not Stormwind and Redridge (different zone id, different subzone)

### CODE REVIEW

**Comment by zdeyn** [comment]
Code is untestecd, would appreciate a logic check and/or an in-game run

**Comment by aaronma37** [comment]
Double check that parent ids are not continent lvl. I think its actually better to remove the failure completely here and just guide the user via warns

**Review by aaronma37 — COMMENTED** [review]
if `GetBestMapForUnit` returns a zone like Elywynn Forest, then its parent will be Eastern Kingdoms.

**Comment by zdeyn** [comment]
Still needs work, so switched to draft

**Pull request closed without merging**
