### PR TITLE
Added ability to show the last words said to on death guild message

### PR DESCRIPTION
**Pull request by danaguilar**
This will give a last words section on the death message given to a guild. It will show the last message typed by the player in either /say, /guild, or /party. The channel this message was given in is being stored as well, though not being used at all currently. Messages will not be saved between sessions and thus a "last words" will only be given if the player has talked in one of those channels during the current play section. It will be skipped otherwise

### CODE REVIEW

**Review by blenderer — APPROVED** [review]
I'm a fan tbh. Would love to see this get merged

I'll handle merge conflicts if needed

**Review by RobertB4 — APPROVED** [review]
Code looks good. Let's wait till other more important pull requests are merged and merge this one after imo.

**Comment by blenderer** [comment]
@danaguilar Unfortunately we had to refactor our death messages to not include custom text, so we're unable to merge this guy for now.

**Comment by danaguilar** [comment]
np. Do you need me to do any more work on this to make it work with the newer death message or are y'all scrapping this idea altogether?

**Comment by blenderer** [comment]
It's good I'm going to merge it as soon as I resolve the merge conflicts!

**Pull request merged**
