### PR TITLE
Request played timed buffer

### PR DESCRIPTION
**Pull request by aaronma37**
solution for played message spam

This is a potential solution; a message buffer is implemented so that if played messages comes back in batches, we will be able to handle hiding more.
#40 

Another solution would be to decrease C_TIMER rate

### CODE REVIEW

**Comment by zdeyn** [comment]
I'll ask the wizards in the lua cave and see what they have to say

**Comment by zdeyn** [comment]
"you can just unregister TIME_PLAYED_MSG from the active chat window before you send the RequestTimePlayed(), and re-register it again after you've handled TIME_PLAYED_MSG - this gets you the data without any display"

**Comment by aaronma37** [comment]
> "you can unregister TIME_PLAYED_MSG from the active chat window before you send the RequestTimePlayed(), and re-register it again after you've handled TIME_PLAYED_MSG - this gets you the data without any display"

I think this will still run into issues with batches? Not sure how it is functionally different than what we currently do

**Comment by zdeyn** [comment]
> Not sure how it is functionally different than what we currently do
From what I understand, it lets you do whatever you want while querying for played time - it just won't be output. By the time you're finished, you've cleaned up after yourself and reconnected the event back to the chat window for when the player types /played maually, or until we need to scan again

**Comment by aaronma37** [comment]
> > Not sure how it is functionally different than what we currently do
> > From what I understand, it lets you do whatever you want while querying for played time - it just won't be output. By the time you're finished, you've cleaned up after yourself and reconnected the event back to the chat window for when the player types /played maually, or until we need to scan again

But if you get two queued up messages, the first one will register the callback again and the second one will display the msg

**Comment by zdeyn** [comment]
> But if you get two queued up messages, the first one will register the callback again and the second one will display the msg

Then perhaps we need to consider it from the other end - why is the queueing up / batching happening?

**Comment by aaronma37** [comment]
> > But if you get two queued up messages, the first one will register the callback again and the second one will display the msg
> 
> Then perhaps we need to consider it from the other end - why is the queueing up / batching happening?

I think it might just happen if it gets requests before it publishes back to the client. So slowing it down would definitely do it. Or queues if we don't want to go slower

**Comment by aaronma37** [comment]
> > > But if you get two queued up messages, the first one will register the callback again and the second one will display the msg
> > 
> > 
> > Then perhaps we need to consider it from the other end - why is the queueing up / batching happening?
> 
> I think it might just happen if it gets requests before it publishes back to the client. So slowing it down would definitely do it. Or queues if we don't want to go slower

For example, we can replicate the issue by speeding up that c timer to 10hz

**Comment by zdeyn** [comment]
> > > But if you get two queued up messages, the first one will register the callback again and the second one will display the msg
> > 
> > 
> > Then perhaps we need to consider it from the other end - why is the queueing up / batching happening?
> 
> I think it might just happen if it gets requests before it publishes back to the client. So slowing it down would definitely do it. 

Slower is good :shrug:

**Comment by aaronma37** [comment]
> > > > But if you get two queued up messages, the first one will register the callback again and the second one will display the msg
> > > 
> > > 
> > > Then perhaps we need to consider it from the other end - why is the queueing up / batching happening?
> > 
> > 
> > I think it might just happen if it gets requests before it publishes back to the client. So slowing it down would definitely do it.
> 
> Slower is good 🤷

Yep! Agreed

**Comment by RobertB4** [comment]
Thanks for looking into this! I think the easiest solution is to stop caching the time played and only request it when we need it (before generating the verification string). The value is stored on blizzards end, so we don't really need to cache it.

**Comment by aaronma37** [comment]
> Thanks for looking into this! I think the easiest solution is to stop caching the time played and only request it when we need it (before generating the verification string). The value is stored on blizzards end, so we don't really need to cache it.

I'm down for that too! but we would have to handle updating the accumulated difference somehow

**Comment by aaronma37** [comment]
> > Thanks for looking into this! I think the easiest solution is to stop caching the time played and only request it when we need it (before generating the verification string). The value is stored on blizzards end, so we don't really need to cache it.
> 
> I'm down for that too! but we would have to handle updating the accumulated difference somehow

If we want to keep using it

**Comment by RobertB4** [comment]
> I'm down for that too! but we would have to handle updating the accumulated difference somehow

Oh yeah, you're right. Not sure if that works. Saving variables on logout does not seem to work properly, or last time I tried I could not make it work.

**Comment by zdeyn** [comment]
Let's take it back a step - the purpose of measuring /played vs addons opinion of played was intended to confirm the addon has been enabled at least a significant proportion of the time (within error margin of perfect)

With that reminder, can we instead check for unexplained gaps? What did we last see, and what do we see now? What's changed,  and what does that tell us?

**Review by RobertB4 — APPROVED** [review]
Let's keep the buffer for now.
After release, let's rethink if there is a better way to tackle the problems we need the /played for.

**Review by blenderer — APPROVED** [review]

**Pull request merged**
