### PR TITLE
(WIP for comments only) Texture swap support

### PR DESCRIPTION
**Pull request by aaronma37**
Support for animations and texture swapping
* PlayerFrames
* PetFrames
* PartyFrames
* TargetFrames
* ToTFrames
* Minimap
* Adding general textures

Also has initial logic for swapping textures based on target's HC status

If reviewing, please ignore BlizzardOptions.xml and TempOptionsConfig.lua; they are just there for testing purposes.

### CODE REVIEW

**Comment by zdeyn** [comment]
My main concern with the feature is 'easy to enable/disable', as I use a custom UI (ElvUI) which I don't believe benefits from much of your work (as almost everything is already replaced)

I'm happy to help ensure it plays friendly with many configurations

**Comment by RobertB4** [comment]
> My main concern with the feature is 'easy to enable/disable', as I use a custom UI (ElvUI) which I don't believe benefits from much of your work (as almost everything is already replaced)
I'm happy to help ensure it plays friendly with many configurations

How much work would this be? If it takes a while to implement, I'd say just leave it as is. If players want to use the hardcore textures, they will have to refrain from using ElvUI and similar.

If you can quickly implement it it would be cool to have though!

**Comment by zdeyn** [comment]
It'd just be a setting in the addon config - "Enhanced Unit / Target Frames: Enabled/Disabled", which would provide you with a true / false behind which you gate all your enhancement code - simple boolean checks at the right times and the on/off handles itself

**Comment by blenderer** [comment]
No need for configuration support. Should fail silently if the frame is hidden

**Comment by zdeyn** [comment]
Does "Fail silently" allow people to choose not to use it? People are picky about their UIs, even even someone using the default frames may simply choose to keep the previous behaviour... enable/disable is the right solution here, imo

**Comment by aaronma37** [comment]
> My main concern with the feature is 'easy to enable/disable', as I use a custom UI (ElvUI) which I don't believe benefits from much of your work (as almost everything is already replaced)
> 
> I'm happy to help ensure it plays friendly with many configurations

That would be great! My intention is to no-op if configuration options are set to the blizzards default. That way it shouldn't interfere with another addon. It does seem to work fine with moveanything as is though. I haven't tested elvui

**Comment by aaronma37** [comment]
> > My main concern with the feature is 'easy to enable/disable', as I use a custom UI (ElvUI) which I don't believe benefits from much of your work (as almost everything is already replaced)
> > I'm happy to help ensure it plays friendly with many configurations
> 
> That would be great! My intention is to no-op if configuration options are set to the blizzards default. That way it shouldn't interfere with another addon. It does seem to work fine with moveanything as is though. I haven't tested elvui

Imo this PR would require the option configs feature

**Comment by aaronma37** [comment]
> > > My main concern with the feature is 'easy to enable/disable', as I use a custom UI (ElvUI) which I don't believe benefits from much of your work (as almost everything is already replaced)
> > > I'm happy to help ensure it plays friendly with many configurations
> > 
> > 
> > That would be great! My intention is to no-op if configuration options are set to the blizzards default. That way it shouldn't interfere with another addon. It does seem to work fine with moveanything as is though. I haven't tested elvui
> 
> Imo this PR would require the option configs feature

Example; we would no-op for each frame on reload if default settings
image

**Comment by zdeyn** [comment]
> > > > My main concern with the feature is 'easy to enable/disable', as I use a custom UI (ElvUI) which I don't believe benefits from much of your work (as almost everything is already replaced)
> > > > I'm happy to help ensure it plays friendly with many configurations
> > > 
> > > 
> > > That would be great! My intention is to no-op if configuration options are set to the blizzards default. That way it shouldn't interfere with another addon. It does seem to work fine with moveanything as is though. I haven't tested elvui
> > 
> > 
> > Imo this PR would require the option configs feature
> 
> Example; we would no-op for each frame on reload if default settings image

This captures my intent perfectly - thankyou

**Pull request closed without merging**
