### PR TITLE
Basic integration with GreenWall

### PR DESCRIPTION
**Pull request by GrumpyPlayer**
An addon like GreenWall, that affects guild communications, is something you want everyone or nobody to have enabled in my opinion. That would be the sole reason I recommend including it in the core. I'm assuming that with an additional addon dependent on HC you would have some people disabling it, and seeing people reply to messages in their guild chat without the context of the federated messages is annoying. When an addon that requires zero configuration from anyone but the officers, I think it makes more sense to fully embed it.

Steps I took:
- Copied in most files from the Greenwall addon
- Updated the Hardcore.toc for demonstration purposes
- Renamed the commands to listen to hardcore_greenwall and hc_gw instead
- Told the GreenWall addon to listen to the loading of the Hardcore addon instead
- Changed the chat prefix for GreenWall to state Hardcore-GreenWall in the Hardcore color
- Changed the chat prefix (but not the color) for the officer and debug messages
- Renamed the addon interface options screen to state "Hardcore: GreenWall"
- Embedded the libraries like the Hardcore addon is structured

The result:
145134194-1fb6f2b6-383f-4ac0-9b9b-e59d4e4ddd13
145133726-b9632d3b-605a-410e-b5aa-c37d0961c6d7

This is an example setup that needs to be put into the guild information:
unknown1
unknown2

Here's how it looks for regular players:
unknown

Use the in-game commands of /hardcore_greenwall and /hc_gw

If someone else can install it, then we can test it on the Season of Mastery Beta 1 realm (on the Classic Season of Mastery Beta) on which I am the guild master of two different guilds.

### CODE REVIEW

**Comment by GrumpyPlayer** [comment]
@aaronma37 My handle is GrumpyPlayer#6657 on Discord. Can you contact me, or let me know your handle, so that we can jump on the beta at some point to test a few things?

**Comment by aaronma37** [comment]
Could we just use a  custom channel for global notifications? I imagine there are guilds that want that, but wouldn't  want full gw integration

**Comment by GrumpyPlayer** [comment]
That kind of defeats the purpose of GreenWall and the objective I was hoping to contribute to: allow the entire community (those that are leveling) to communicate with each other in-game with ease irrespective of the hard limit of 1000 players in a guild.

If using something like this exclusively for global notifications is truly desired, it ought to be defined what those notifications are. With some work, I suppose we could make the sharing of the guild chat an optional configuration. 

Either way, we could still use the GreenWall API for building other distributed applications for guild confederations.
See https://github.com/AIE-Guild/GWSonar, which alows a user to send a hidden request message to other members of the confederation. Other instances of the add-on will respond and the requesting can view response time metrics.

**Comment by aaronma37** [comment]
> That kind of defeats the purpose of GreenWall and the objective I was hoping to contribute to: allow the entire community (those that are leveling) to communicate with each other in-game with ease, irrespective of the hard limit of 1000 players in a guild.
> 
> If using something like this exclusively for global notifications is truly desired, it ought to be defined what those notifications are. With some work, I suppose we could make the sharing of the guild chat an optional configuration.
> 
> Either way, we could still use the GreenWall API for building other distributed applications for guild confederations. See https://github.com/AIE-Guild/GWSonar, which alows a user to send a hidden request message to other members of the confederation. Other instances of the add-on will respond and the requesting can view response time metrics.

I personally prefer having the community all in one guild, but I think it's something that needs agreement on beyond the hc addon development team since it would cause some restructuring within the community. Maybe we could elevate this?

Some options
1) 1 gw guild per server
2) global alerts (using sonar maybe) + gw separately for those that want globbed  guilds

**Comment by GrumpyPlayer** [comment]
If we take season of mastery as an example, there will be *n* number of guilds per realm for leveling per faction. Currently, for Alliance, there are 6 for NA and 5 for EU. Since across region, across faction, and across realms that are not connected this federation is impossible: it would be to connect the 6 Alliance leveling guilds on NA-Obsidian Edge, and the 5 Alliance leveling guilds on EU-Quel'Serrar as the primary objective.

Can you clarify what type of restructuring you see? I'm not seeing any.

If there's a desire to pursue this, the decisions to be made are:
1. Do you want all guild communication to be federated across multiple guilds of the same faction during season of mastery? If so, which guilds from what realm?
2. Do you want certain communications to be federated across multiple guilds of the same faction during season of mastery? If so, what types of communication, made by whom?

How can we elevate this? Feel free to contact me on Discord to discuss further.

**Pull request closed without merging**
