### PR TITLE
Agree to HC contract to play

### PR DESCRIPTION
**Pull request by zdeyn**
image

By clicking the button below, you agree to the following statements:
- I have read the rules,
- I have read the FAQ,
- I understand that disconnect appeal approval requires video of both pre-disconnect activity and the reconnect/login process,
- I accept responsibility for /reloading regularly and logging out cleanly to protect my data,
- I understand that buffing a PvP-flagged player will cause me to become PvP-flagged, and I may die.

The recent influx of players has brought to our attention the gap between assumed knowledge and "what players actually know/do". By placing the above directly in front of people prior to beginning their adventure every character, we leave no excuses.

Exact dot-points are my own work, but open to discussion as to what they should be. These are just the most commonly-seen in my experience!

### CODE REVIEW

**Comment by mmobeus** [comment]
Nice. Would be good to have the Rules tab visible here?

**Comment by zdeyn** [comment]
Perhaps just indicate where rules/faq can be read - Discord deets?

**Comment by mmobeus** [comment]
That works. I think in a perfect world, it would point to the website, and the website would have updated rules/faq and discord details. But that sounds like a different effort, so anything stating where they can be found makes sense.

**Comment by zdeyn** [comment]
To be frank, the website doesn't link to the discord very prominently; it's just a small icon in the header, and not very discoverable. `https://discord.gg/5QayTem` isn't something easily typed from the addon, whereas `classichc.net` is.

Ideally, the front page would have a big call-to-action to bring people to the discord as a 'ready to play?' style invitation, and then the discord takes them through ensuring they understand the same 'hardcore contract' as the addon. This is however out-of-scope, 

A button that pops up a small edit-box so they can copy/paste the discord address would work to solve this use-case.

**Comment by zdeyn** [comment]
image

Definitely needs a button, that's not readable

**Comment by zdeyn** [comment]
image

Final version to meet minimum requirements - am adding a button next to/near discord that lets people copy/paste, but since we're using the short-form discord.gg/classichc it's easy to type and thus solves the problem

**Comment by zdeyn** [comment]
image
image

 This is good-to-go

**Comment by zdeyn** [comment]
image

Due to ToS constraints, we can't have the url or a link in the addon itself

this is the best we can do for now, sorry!

**Pull request merged**
