### PR TITLE
Made frame draggable and added an alert toggle

### PR DESCRIPTION
**Pull request by cloudbells**

### CODE REVIEW

**Comment by aaronma37** [comment]
Should we separate this into 2 PRs? Since are somewhat in a code freeze and just merge the urgent one

**Comment by blenderer** [comment]
@aaronma37 The draggable doesn't seem very risky to also add so I wouldn't mind

**Comment by cloudbells** [comment]
Added the griefing fix.

It will check who sent the addon message (ADD) and iterate through the guild roster. If it finds a player with the same name as the sender of the addon message, it gets that player's info directly from the guild roster and then prints it. No custom messages are sent.

/Now the only way to grief is by sending messages through guild chat, but that can already be done just by typing in game.)

**Comment by aaronma37** [comment]
> Added the griefing fix.
> 
> It will check who sent the addon message (ADD) and iterate through the guild roster. If it finds a player with the same name as the sender of the addon message, it gets that player's info directly from the guild roster and then prints it. No custom messages are sent.
> 
> (Now the only way to grief is by sending messages through guild chat, but that can already be done just by typing in game.)
> 
> So to sum up:
> 
> * Made the frame draggable.
> * Added a toggle for showing death alerts.
> * Removed the possibility to send custom addon messages that would be displayed on every addon user's screen (griefable by sending rude words)

It seems like we lose the ability to show who killed the player with this, which I think is a pretty liked feature.  We could alternatively send the npc via id

**Comment by blenderer** [comment]
I'm going to add Killed by support and deprecate the old command to this PR

Appreciate the help @cloudbells

**Comment by cloudbells** [comment]
> > Added the griefing fix.
> > It will check who sent the addon message (ADD) and iterate through the guild roster. If it finds a player with the same name as the sender of the addon message, it gets that player's info directly from the guild roster and then prints it. No custom messages are sent.
> > (Now the only way to grief is by sending messages through guild chat, but that can already be done just by typing in game.)
> > So to sum up:
> > 
> > * Made the frame draggable.
> > * Added a toggle for showing death alerts.
> > * Removed the possibility to send custom addon messages that would be displayed on every addon user's screen (griefable by sending rude words)
> 
> It seems like we lose the ability to show who killed the player with this, which I think is a pretty liked feature. We could alternatively send the npc via id

Was the NPC always shown in the alert frame? Or just in guild message? 

https://github.com/Zarant/WoW_Hardcore/blob/299f787d171f579a11b0bc705d17ab34f51b3d6e/Hardcore.lua#L801

**Comment by blenderer** [comment]
Oh true, I think its just the guild message

**Comment by cloudbells** [comment]
> I'm going to add Killed by support and deprecate the old command to this PR
> 
> Appreciate the help @cloudbells

As long as it's not another string, as that can also be abused :( Not entirely sure if it's possible to get a name from an NPC ID.

**Comment by aaronma37** [comment]
> Oh true, I think its just the guild message

Ah! I hadn't noticed. I think this sort of approach seems like it would work. It would be nice to use the data payload though in the future :P

**Comment by aaronma37** [comment]
> > I'm going to add Killed by support and deprecate the old command to this PR
> > Appreciate the help @cloudbells
> 
> As long as it's not another string, as that can also be abused :( Not entirely sure if it's possible to get a name from an NPC ID.

Good point, at least not easily

**Comment by blenderer** [comment]
Piggybacked on to this and moved your commits over to: https://github.com/Zarant/WoW_Hardcore/pull/64

**Pull request closed without merging**
