### PR TITLE
Add mult-pc support warning to README

### PR DESCRIPTION
**Pull request by blenderer**
Updates Readme.md for "multi-client support"

### CODE REVIEW

**Review by RobertB4 — COMMENTED** [review]
Looks good! What do you think about adding a sentence explaining that if saved variables are not synced, chances are the character gets flagged with a violation?

Example:
Due to technical limitations of WoW addons, forgetting to or purposely not syncing the Saved Variables file can result in your character getting flagged for rule violation.

**Comment by blenderer** [comment]
image

@RobertB4 What do you think of this? A little more to the point without specifics.

**Review by RobertB4 — APPROVED** [review]
I like it, gives the users a warning and explains what they have to do 👍

**Comment by zdeyn** [comment]
perhaps "The consequence of this is potentially losing VERIFIED status!" could be said, "The consequence of this is potentially being unverified through automatic means - a full-run video would be required."

e.g. solve it properly, or record your entire run - options are provided, alternatives, etc player's problem from there

As for the warning - it's great - love it.

**Review by zdeyn — APPROVED** [review]
Other than my suggestion in my prior comment, I love it

**Pull request merged**
